function help_compile_iter_window_manual_mask_specify()

    hs = findall(0,'tag','helpManualMask');
    if (isempty(hs))
        hs = add_help_compile_iter_window_manual_mask_specify_components;
        set(hs.fig,'Visible','on');
    else
        figure(hs);
    end
    
    function hs = add_help_compile_iter_window_manual_mask_specify_components
        % Add components, save handles in a struct
        hs.fig = figure('Tag','helpManualMask',...
            'units', 'normalized', 'position', [0.4 0.4 0.2 0.3],...
            'MenuBar', 'none',...
            'NumberTitle','off',...
            'Name','Mask File - Help',...
            'Resize','off',...
            'Visible','off',...
            'Color',get(0,'defaultUicontrolBackgroundColor'),...
            'WindowStyle', 'modal');
        
        helpString = fileread('help_compile_iter_window_manual_mask.txt');
        
        mainHelpTextbox = uicontrol('Style', 'Text', ...
            'Units', 'Normalized', ...
            'String', helpString,...
            'Position', [0.0, 0.0, 1, 1], ...
            'HorizontalAlignment', 'Left'); %#ok<NASGU>
        
        CloseButton = uicontrol('Style', 'pushbutton', ...
            'String', 'Close', ...
            'Units', 'Normalized', ...
            'Position', [0.9, 0.01, 0.08, 0.05], ...
            'Tag', 'CancelButton',...
            'callback', @close_button_callback ); %#ok<NASGU>
        
    end

    function close_button_callback(src, event)
        delete(src.Parent);
    end


end

